<a href="https://colab.research.google.com/github/pri265126-stack/delhi-uber-eda/blob/main/aws_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Delhi Uber Ride Dataset — Exploratory Data Analysis (EDA)

### ML Domain Task

**Prepared by:** Priya Tiwari

## Objective

The goal of this project is to perform Exploratory Data Analysis (EDA) on a Delhi Uber ride dataset to understand booking patterns, identify inconsistencies in the data, clean missing values, visualize important trends, and derive meaningful business insights.

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 1: Load the Dataset

In this step, we load the Delhi Uber ride dataset into a Pandas DataFrame and preview the first few records.

In [3]:
import pandas as pd

df = pd.read_csv("/content/delhi_uber_dataset aws")

df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2025-09-23,21:25:15,UBR197645,Driver Cancelled,cust23444,Uber Auto,Lajpat Nagar,Noida Sector 62,2.2,-,NaN,Yes,Too far,NO,NaN,NaN,16.5,NaN,NaN,Credit Card
1,2025-10-13,16:36:45,UBR140756,Completed,CUST65862,Uber Go,Aerocity,Vasant Kunj,3.8,29.1,NaN,NO,NaN,NO,NaN,511.6,25.9,3.7,4.6,Unknown
2,11-03-2025,NaN,UBR152026,Completed,CUST72140,Moto,Faridabad,Greater Kailash,90.0,49.9,NaN,NO,NaN,NO,NaN,135.8,5.7,4.4,4.7,Debit Card
3,NaN,16:59:32,UBR109526,Incomplete,CUST67783,Uber Auto,Ghaziabad,Saket,8.4,23.3,NaN,NO,NaN,Yes,NaN,NaN,10.8,NaN,NaN,upi
4,2025-07-16,23:36:10,UBR170351,Completed,CUST24921,uber xl,Faridabad,Rohini,5.4,16.9,NaN,No,NaN,No,NaN,121.3,3.3,5.0,4.6,debit card

In [4]:
df.shape

(100000, 20)

In [5]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Reason for cancelling by Customer',
       'Cancelled Rides by Driver', 'Driver Cancellation Reason',
       'Incomplete Rides', 'Incomplete Rides Reason', 'Booking Value',
       'Ride Distance', 'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               95976 non-null  object
 1   Time                               96728 non-null  object
 2   Booking ID                         99702 non-null  object
 3   Booking Status                     98678 non-null  object
 4   Customer ID                        95074 non-null  object
 5   Vehicle Type                       95987 non-null  object
 6   Pickup Location                    96643 non-null  object
 7   Drop Location                      96594 non-null  object
 8   Avg VTAT                           93996 non-null  object
 9   Avg CTAT                           90680 non-null  object
 10  Reason for cancelling by Customer  12210 non-null  object
 11  Cancelled Rides by Driver          96703 non-null  object
 12  Driver Cancellation Reason         10768 non-null  object
 13  Incomplete Rides                   96694 non-null  object
 14  Incomplete Rides Reason            10398 non-null  object
 15  Booking Value                      83911 non-null  object
 16  Ride Distance                      82026 non-null  object
 17  Driver Ratings                     66488 non-null  object
 18  Customer Rating                    66785 non-null  object
 19  Payment Method                     92352 non-null  object
dtypes: object(20)
memory usage: 15.3+ MB

## Step 4: Summary Statistics

Generate summary statistics for numerical columns.

In [7]:
df.describe().T

                                   count unique              top   freq
Date                               95976   2193       2025-12-17    253
Time                               96728  53092          Unknown    232
Booking ID                         99702  98645       UBR190410       3
Booking Status                     98678     18        Completed  51160
Customer ID                        95074  50745                -    349
Vehicle Type                       95987     22          Uber Go  23463
Pickup Location                    96643     50  Greater Kailash   3386
Drop Location                      96594     50           Rohini   3375
Avg VTAT                           93996    246                -   1004
Avg CTAT                           90680    561             60.0   8507
Reason for cancelling by Customer  12210     38    Not Available   1150
Cancelled Rides by Driver          96703     11               No  21686
Driver Cancellation Reason         10768     43    Not Available   1149
Incomplete Rides                   96694     11              No   21501
Incomplete Rides Reason            10398     38                -   1130
Booking Value                      83911  10369          unknown   1648
Ride Distance                      82026   2890          unknown   1573
Driver Ratings                     66488   4974              5.0   9987
Customer Rating                    66785   4745              5.0  12092
Payment Method                     92352     15              UPI  28151